server:
  port: 8081
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: ${traveller.datasource.driver-class-name}
      url: jdbc:mysql://${traveller.datasource.host}:${traveller.datasource.port}/${traveller.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${traveller.datasource.username}
      password: ${traveller.datasource.password}
      min-idle: 3
  redis:
    port: ${traveller.redis.port}
    host: ${traveller.redis.host}
  mail:
    #smtp服务主机  qq邮箱则为smtp.qq.com
    host: ${traveller.mail.host}
    #服务协议
    protocol: ${traveller.mail.protocol}
    # 编码集
    default-encoding: UTF-8
    #发送邮件的账户
    username: ${traveller.mail.username}
    #授权码
    password: ${traveller.mail.password}
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.traveller.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

traveller:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    secret-key: traveller-TBlog
    # 设置jwt过期时间
    ttl: 36000000
    # 设置前端传递过来的令牌名称
    token-name: token

blog:
  name: 旅人

